import { useEffect, useMemo, useState } from 'react'
import { useAppDispatch, useAppSelector } from '@/app/hooks'
import { fetchUsersThunk } from '@/features/users/usersSlice'
import { fetchActivityThunk } from '@/features/activity/activitySlice'
import { fetchMonthsThunk, fetchRecordThunk } from '@/features/records/recordsSlice'
import { fetchSubAccountsThunk } from '@/features/subAccounts/subAccountsSlice'
import { Button } from '@/components/Button'
import { Select } from '@/components/Select'
import { Table, Td, Th } from '@/components/Table'
import { formatMoney } from '@/utils/currency'
import { formatISODate } from '@/utils/date'

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export default function DoubleColumnLedger() {
  const dispatch = useAppDispatch()

  const { months, current, loading } = useAppSelector((state) => state.records)
  const [selectedMonth, setSelectedMonth] = useState('')

  const authUid = useAppSelector((state) => state.auth.user?.uid)
  const users = useAppSelector((state) => state.users.items)
  const currentUser = users.find((u) => u.uid === authUid)

  // Sub accounts in Redux (we also fetch them so UI always has names)
  const subAccounts = useAppSelector((state) => state.subAccounts.items)

  useEffect(() => {
    dispatch(fetchUsersThunk())
    // dispatch(fetchActivityThunk())
    dispatch(fetchMonthsThunk())
    // dispatch(fetchSubAccountsThunk())
  }, [dispatch])

  useEffect(() => {
    if (months.length && !selectedMonth) setSelectedMonth(months[0])
  }, [months, selectedMonth])

  useEffect(() => {
    console.log('=================lllll ', selectedMonth);
    if (selectedMonth) dispatch(fetchRecordThunk(selectedMonth))
  }, [dispatch, selectedMonth])

  const totals = useMemo(() => {
    if (!current) return { debit: 0, credit: 0 }
    let debit = 0
    let credit = 0
    for (const e of current.entries) {
      if (typeof e.debit === 'number') debit += e.debit
      if (typeof e.credit === 'number') credit += e.credit
    }
    return { debit, credit }
  }, [current])

  function onPrintPdf() {
    if (!current) return

    const doc = new jsPDF('p', 'mm', 'a4')

    // Header
    doc.setFontSize(16)
    doc.text('Double Column Ledger', 14, 16)

    doc.setFontSize(11)
    doc.text(`Month: ${current.month}`, 14, 24)
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30)
    doc.text(`Generated by: ${currentUser?.name ?? 'Admin'}`, 14, 36)

    // Summary boxes (simple & clean)
    doc.setFontSize(12)
    doc.text(`Opening Balance: ${formatMoney(current.openingBalance)}`, 14, 46)
    doc.text(`Closing Balance: ${formatMoney(current.closingBalance)}`, 14, 54)

    doc.setFontSize(11)
    doc.text(`Total Debit: ${formatMoney(totals.debit)}`, 14, 64)
    doc.text(`Total Credit: ${formatMoney(totals.credit)}`, 14, 72)

    // Table data
    const body = current.entries.map((e) => [
      formatISODate(e.date),
      e.description || '',
      e.subAccountName || '',
      e.debit ? formatMoney(e.debit) : '',
      e.credit ? formatMoney(e.credit) : '',
    ])

    autoTable(doc, {
      startY: 80,
      head: [['Date', 'Description', 'Sub Account', 'Debit', 'Credit']],
      body,
      styles: {
        fontSize: 9,
        cellPadding: 2,
        overflow: 'linebreak',
      },
      headStyles: {
        fillColor: [15, 23, 42], // slate-900
        textColor: 255,
      },
      columnStyles: {
        0: { cellWidth: 22 }, // Date
        1: { cellWidth: 70 }, // Desc
        2: { cellWidth: 38 }, // Sub
        3: { halign: 'right', cellWidth: 28 }, // Debit
        4: { halign: 'right', cellWidth: 28 }, // Credit
      },
      didDrawPage: (data) => {
        const pageCount = doc.getNumberOfPages()
        doc.setFontSize(9)
        doc.text(
          `Page ${doc.getCurrentPageInfo().pageNumber} of ${pageCount}`,
          190,
          290,
          { align: 'right' }
        )
      },
    })

    doc.save(`DoubleColumnLedger_${current.month}.pdf`)
  }

  return (
    <div className="page space-y-6">
      <div className="card p-6">
        <div className="text-xl font-semibold">{currentUser?.role}</div>
        <div className="mt-1 text-sm text-slate-600">
          Hello, {currentUser?.name ?? 'Admin'} !!
        </div>
      </div>

      <div className="card p-6">
        <div className="flex items-center justify-between gap-3">
          <div>
            <div className="text-lg font-semibold">Financial records</div>
            <div className="mt-1 text-sm text-slate-600">
              Double Column Accounting Book by month
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Select value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)}>
              {months.length ? (
                months.map((m) => (
                  <option key={m} value={m}>
                    {m}
                  </option>
                ))
              ) : (
                <option value="">No months yet</option>
              )}
            </Select>

            <Button
              variant="secondary"
              loading={loading}
              onClick={() => selectedMonth && dispatch(fetchRecordThunk(selectedMonth))}
            >
              Reload
            </Button>
          </div>
        </div>

        <div className="mt-4">
          {current ? (
            <div className="space-y-3">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="card p-4">
                  <div className="text-xs text-slate-500">Opening balance</div>
                  <div className="text-lg font-semibold">{formatMoney(current.openingBalance)}</div>
                </div>
                <div className="card p-4">
                  <div className="text-xs text-slate-500">Closing balance</div>
                  <div className="text-lg font-semibold">{formatMoney(current.closingBalance)}</div>
                </div>
              </div>

              <Table>
                <thead>
                  <tr>
                    <Th>Date</Th>
                    <Th>Description</Th>
                    <Th>Sub Account</Th>
                    <Th>Debit</Th>
                    <Th>Credit</Th>
                  </tr>
                </thead>

                <tbody>
                  {current.entries.map((e) => (
                    <tr key={e.transactionId}>
                      <Td>{formatISODate(e.date)}</Td>
                      <Td>{e.description}</Td>
                      <Td>{e.subAccountName}</Td>
                      <Td>{e.debit ? formatMoney(e.debit) : ''}</Td>
                      <Td>{e.credit ? formatMoney(e.credit) : ''}</Td>
                    </tr>
                  ))}

                  {current.entries.length === 0 ? (
                    <tr>
                      <Td>
                        <span className="text-slate-500">No entries.</span>
                      </Td>
                      <Td />
                      <Td />
                      <Td />
                      <Td />
                    </tr>
                  ) : null}

                  {/* Totals row */}
                  {current.entries.length > 0 ? (
                    <tr className="border-t">
                      <Td />
                      <Td />
                      <Td>
                        <span className="text-sm font-semibold">Totals</span>
                      </Td>
                      <Td>
                        <span className="text-sm font-semibold">{formatMoney(totals.debit)}</span>
                      </Td>
                      <Td>
                        <span className="text-sm font-semibold">{formatMoney(totals.credit)}</span>
                      </Td>
                    </tr>
                  ) : null}
                </tbody>
              </Table>

              {/* ✅ Print button bottom-left */}
              <div className="flex justify-start pt-2">
                <Button onClick={onPrintPdf} disabled={!current || loading}>
                  Print PDF
                </Button>
              </div>
            </div>
          ) : (
            <div className="text-sm text-slate-600">No record found for this month.</div>
          )}
        </div>
      </div>
    </div>
  )
}
